# Generated by Django 4.2.4 on 2023-09-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0001_initial"),
        ("zw", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="zp_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="zp.profile", unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zw_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="zw.profile", unique=True
            ),
        ),
    ]
