# Generated by Django 4.2.7 on 2023-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0005_alter_profile_profile_alter_profilesignups_signups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllResults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("results", models.JSONField(null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventResultsView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zp_id", models.IntegerField()),
                ("results", models.JSONField(null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventResultsZwift",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zp_id", models.IntegerField()),
                ("results", models.JSONField(null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
