# Generated by Django 4.2.7 on 2023-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0006_allresults_eventresultsview_eventresultszwift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventresultsview",
            name="zp_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="eventresultszwift",
            name="zp_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zp_id",
            field=models.IntegerField(unique=True),
        ),
    ]
