# Generated by Django 4.2.7 on 2023-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0007_alter_eventresultsview_zp_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profilesignups",
            name="error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="profilevictims",
            name="error",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
