# Generated by Django 4.2.7 on 2023-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0013_rename_results_allresults_event_allresults_errors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.JSONField(default={"last_event": 0, "needs_update": True}, null=True),
        ),
    ]
