# Generated by Django 4.2.7 on 2023-11-21 01:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0015_results_zp_view_results_zp_zwift_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileSignups",
        ),
        migrations.DeleteModel(
            name="ProfileVictims",
        ),
    ]
