# Generated by Django 4.2.7 on 2023-11-21 14:31

import apps.zp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0016_delete_profilesignups_delete_profilevictims"),
    ]

    operations = [
        migrations.AddField(
            model_name="allresults",
            name="view",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="allresults",
            name="zwift",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="status",
            field=models.JSONField(default=apps.zp.models.Profile.default_status, null=True),
        ),
    ]
