# Generated by Django 4.2.7 on 2023-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zp", "0017_allresults_view_allresults_zwift_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allresults",
            name="event_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="allresults",
            name="race_history",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="results",
            name="race_history",
            field=models.JSONField(null=True),
        ),
    ]
