# Generated by Django 4.2.4 on 2023-09-18 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("zp", "0001_initial"),
        ("zw", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("team_name", models.CharField(max_length=255)),
                ("zp_id", models.IntegerField(blank=True, unique=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pending",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="zp.teampending"),
                ),
                (
                    "results",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="zp.teamresults"),
                ),
                (
                    "riders",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="zp.teamriders"),
                ),
                ("zw_id", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="zw.profile")),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=255,
                    ),
                ),
                ("is_owner", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("team", models.ManyToManyField(to="teams.team")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
