# Generated by Django 4.2.6 on 2023-11-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_remove_team_pending_remove_team_results_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="zp_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Zwift Power ID"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="zw_id",
            field=models.CharField(
                blank=True, default="", unique=True, verbose_name="Zwift Club name"
            ),
        ),
    ]
