# Generated by Django 4.2.6 on 2023-11-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_alter_team_zp_id_alter_team_zw_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="zw_id",
            field=models.CharField(blank=True, default="", unique=True, verbose_name="Zwift Club Name"),
        ),
    ]
